### PR TITLE
Add support for aarch64

### PR DESCRIPTION
**Pull request by cinemast**

### CODE REVIEW

**Comment by benweissmann** [comment]
Hi @cinemast! Thanks for submitting your first PR!

As you can see from the CI checks, it looks like there's some syntax errors in your code.

Unfortunately, I don't have an aarch64 machine to test this on. But that's OK! I'm happy to have you give it a thorough test if you have an aarch64 machine to test on. Could you post as testing documentation:

- Details of the machine you've tested this on
- A screen recording of running the script on that machine, and then running the resulting `micro` binary to confirm that it all works?

I'm definitely excited about adding arm64 support! But I'm also pretty conservative in terms of making sure this project is robust and doesn't break for existing users, and almost all arm64 system can run legacy arm binaries, so I just want to be very sure that this isn't going to break for any existing arm64 users who are currently using getmic.ro.

**Comment by benweissmann** [comment]
Just wanted to follow up and let you know I've added a bunch more platforms to the CI tests, including 32-bit and 64-bit ARM. If you merge the latest changes into your branch, github will automatically test your code on ARM!

**Comment by cinemast** [comment]
Wow! Nice test suite.
It appears to look good: https://github.com/benweissmann/getmic.ro/pull/13/checks?check_run_id=687061278

I was using it on an ODROID-N2 running archlinuxarm.

**Comment by benweissmann** [comment]
Looks great, thank you!

**Pull request merged**
