### PR TITLE
run update alternatives after download

### LINKED ISSUE #30: update-alternatives does not work at all
trying to use update-alternative fails because the path it tries to use does not exist.
I believe this is the case because the script tries to install micro as an alternative editor before even downloading micro.

script log below
```
root@machine:~# cd /usr/local/bin/
root@machine:/usr/local/bin# curl https://getmic.ro | sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 10066  100 10066    0     0  57850      0 --:--:-- --:--:-- --:--:-- 57850
Detected platform: linux64
/=====================================\\
|     update-alternatives detected     |
\\=====================================/

getmicro can use update-alternatives to register micro as a system text editor.
For example, this will allow `crontab -e` open the cron file with micro.

To avoid this prompt in the future, define the GETMICRO_REGISTER variable. E.x:

  $ curl https://getmic.ro | GETMICRO_REGISTER=y sh

Many people find it useful to make micro available on the PATH. One way to do
 this is to enter a root shell and run `cd /usr/bin` prior to installation.

Register '/usr/local/bin/micro' with update-alternatives [y/n]: y

Installing '/usr/local/bin/micro' as /usr/bin/editor...
update-alternatives: error: alternative path /usr/local/bin/micro doesn't exist
root@machine:/usr/local/bin#
```

### PR DESCRIPTION
**Pull request by fgardt**
## Description

Moved the update-alternatives block to be run after the download & unzip of micro.
This fixes #30.

## How Has This Been Tested?

Run `curl https://raw.githubusercontent.com/Brain-Gamer/getmic.ro/fix_update-alternatives/index.sh | sh` and answer the `Register '/your/path/micro' with update-alternatives [y/n]:` with `y`.

Previously the script failed but with this change it completes and installs micro successfully.

## Checklist:

- [ ] ~I have commented my code, particularly in hard-to-understand areas~
- [ ] ~If I added new user-facing functionality, I have made corresponding changes to the README documenting the changes~
- [ ] ~If this is a code change, I have updated the [test configuration](https://github.com/benweissmann/getmic.ro/blob/master/.github/workflows/test.yml) and/or [test scripts](https://github.com/benweissmann/getmic.ro/tree/master/ci) to cover the changes I've made.~

These do not really apply since the only change was to move one code block below another one.

### CODE REVIEW

**Comment by benweissmann** [comment]
@anonyco Just wanted to flag this for you -- I had tested this and it was working, but I think maybe both of us were testing with a previous copy of `micro` already downloaded to `$PWD`? I'm going to go ahead and merge this but let me know if you have any concerns.

@Brain-Gamer thanks so much! This looks great.

**Comment by fgardt** [comment]
Yeah my guess also was that the interactive tests that had been done for #28 already had a copy of micro installed at the specified location and that way it didn't fail. 

The CI tests then must default to not using update-alternatives or don't support it at all.
Maybe extra tests for this would be wise but I just wanted a quick fix since a docker image build from me depends on this and I wanted to use update-alternatives.

*Note: I just changed my github username since that was long overdue* 😅

**Comment by anonyco** [comment]
The issue, it appears, is that the interactive tests did not test the update-alternatives section.

To maintain compatibility with existing systems using getmicro for automated install, the script does not prompt you with the question if there's no interactive TTY, instead defaulting to the previous behavior of not using update-alternatives.

I'm creating some tests that for the update alternatives feature and will open a PR soon.

**Comment by benweissmann** [comment]
That sounds great, thanks @anonyco !

**Pull request merged**
