### PR TITLE
 Make it POSIX compliant | Some misc changes

### PR DESCRIPTION
**Pull request by Akianonymus**

### CODE REVIEW

**Comment by benweissmann** [comment]
Hi @Akianonymus! Thanks for submitting your first PR!

Could you say a little more about what user-facing benefit these changes bring? One challenge with this project is that crafting a shell script that works across a ton of different platforms, versions of bash, etc., requires quite a lot of testing. Different versions of bash can have subtly (or substantially!) different behavior, so I'm pretty conservative in terms of what changes I make that don't bring substantial user benefit -- the code that's there now is battle-tested across a lot of different systems and bash versions, and uses a pretty minimal set of features to maximize compatibility (you'd be surprised how frequently someone aliases `bash` as some other `sh`-compatible shell!). 

That said, if you're interested in working on our CI setup to test against a broader range of bash versions and bash-like shells, that would be an amazing contribution, and make it much easier/lower-risk for me to accept stylistic/maintenance contributions like this one!

**Comment by Akianonymus** [comment]
> Hi @Akianonymus! Thanks for submitting your first PR!

@benweissmann My Pleasure !

> Could you say a little more about what user-facing benefit these changes bring? One challenge with this project is that crafting a shell script that works across a ton of different platforms, versions of bash, etc....

Well, it handles the case when no ostype is detected, now if it's not detected then script asks user for input, now, from this point, there are 2 possibilities:

1. User gives an empty input

This is surely handled by the set -u option as it will exit the script by saying inbound varible, so i just added a check and properly print what's exactly happened.

2. User gives some input but the input is not one the platform that `micro` supports

This is not handled by the script, and it tried to download from and broken link and errors.

Handled that case and print to user what exactly happened.

About your argument about bash versions, I don't think i have used anything that would break in any bash versions, obviously i am not talking about ancient bash versions, but it's going to work in bash versions > 2.x, which is still ancient.

The different behaviour point you are talking about, i don't know what those are but would like to know.

Now, about the aliasing of bash to sh, well, i some serious points:

1.  If you want to make a posix compliant script, do that, if you use the bash shebang, then bash is necessary.

2.  Even the current master branch script won't work in posix environment because you are using OSTYPE varible which is only available in bash, dash, zsh and some similar modern shells. One other bash specific feature is set -o pipefail.

What i am trying to say is one should avoid ambiguity, if one wants a posix compliant script, then should follow that.

> That said, if you're interested in working on our CI setup to test against a broader range of bash versions and bash-like shells, that would be an amazing contribution, and make it much easier/lower-risk for me to accept stylistic/maintenance contributions like this one!

Well, as you read my previous point, the mext step would be to make this script as POSIX compliant, then will surely work in all shells.

I would love to help but i need the output of `uname` output of all the supported platforms.

Then we can actually avoid the use of OSTYPE varible and make pure posix.

Also, i have pushed some changes from the last commit making it compatible to posix as much as possible, just OSTYPE is a problem now.

After i get the `uname` outputs, will do the rest required changes and changing the shebang to `sh`.

**Comment by Akianonymus** [comment]
Now the script is fully POSIX compliant

Changes in my commit:

* use `uname -s` for detection of os type ( OSTYPE is not available in POSIX )

For refrence: https://en.m.wikipedia.org/wiki/Uname

* Don't use set -o pipefail as not supported by POSIX.

* Use functionname() instead of function functioname() ( POSIX not supported )

* In case platform is not detected, exit the script if provided input afterwards is empty or not supported

* use printf instesd of cat and echo

* use case instead of test in detection of machine type

* change scripts for POSIX

**Comment by benweissmann** [comment]
Thanks for all these updates! It is going to take me a bit of time to test this against the full set of test environments I have to make sure it works with the various BSDs, etc. I'm trying to get that all working in CI, so it may take a day or two.

I think all the changes to make this more POSIX-compliant are great, but I think I'd rather hedge our bets and still have the docs and shebang specify `bash`, just to reduce the variance between system. I think if I was building this again from scratch I might go for full `sh` compatibility and specify `sh` as the shebang, but again I'm trying to make sure that this doesn't break for the folks who are currently using it, and I think that the best way to do that is to try and be as broadly compatible as possible, but still encourage users to use `bash`.

I'll follow up in a day or two once I've gotten the full cross-platform test suite working (Github Actions theoretically supports running vagrant boxes, so hopefully it shouldn't be too hard)

**Comment by Akianonymus** [comment]
> I think all the changes to make this more POSIX-compliant are great .....

Well, i see you stil have doubts, read this.

http://sites.harvard.edu/~lib113/reference/unix/portable_scripting.html

The whole point is to not break anything.

Also, I don't see a point keeping bash as a shebang when your script is POSIX, that's just straight misleading.

When we talk about robustness, this is what we are talking about, it's either 0 or 1, not 0.5.

and this is as much compatible it gets, as far as i know.

Again, all my arguments and so called fact checks i am giving are only valid if it works out alright.

Check out this project for more information: https://github.com/nvm-sh

> I'll follow up in a day or two once I've gotten the full cross-platform test suite working (Github Actions theoretically supports running vagrant boxes, so hopefully it shouldn't be too hard)

That's great, I will wait, neither me or the script is running :p

**Comment by Akianonymus** [comment]
Seems like the test have passed

and i think i should add test for other shells, like zsh, dash, ksh

any thoughts ? 🤔

**Comment by benweissmann** [comment]
Yeah, adding tests for other shells would be great! You should be able to follow to model of the docker tests in there -- I think `zsh`, `dash`, and `ksh` on ubuntu, and `busybox` on alpine. But I think it's also fine to merge this in without those tests and add them later.

One unfortunate thing I realized as I was adding the tests -- interactivity doesn't work in a `curl | bash`! You can try this out by running this as `cat index.sh | sh` instead of `sh index.sh` -- because the script is going over stdin, you can't prompt for input. I've altered the main script to just tell you to set an environment variable -- could you make your new code just validate that environment variable rather than prompting interactively?

And with respect to `sh` vs. `bash`:
- I'm on board with changing the main shebang to `#! /bin/sh` now that it's POSIX-compliant
- I'd like to keep the README as `curl https://getmic.ro | bash`. Even though it's now portable, I still think that for the majority of users that have `bash`, it's going to be more reliable to run it that way because we have so much testing infrastructure testing `bash` -- now at 22 different OS/platform combinations and counting.
- I don't think we need to change the scripts in `ci/` to use `sh` instead of `bash`; those are internal so I don't think the additional work of keeping them portable is worth is, given that they only run in our controlled CI environments

**Comment by benweissmann** [comment]
If you do want to go down the road of testing other POSIX shells, I made the `ci/runTest.sh` script parameterized with what shell to test to help out with that! But again, I'm happy to merge this work without those tests and add them later. I really do appreciate all the work you've put into this; I'm not trying to be difficult!

**Comment by Akianonymus** [comment]
You don't need cat to make a script work interactively, you use shellname -i scriptname

bash -i index.sh

Before i try to give some more time to this, lemme clarify some things:

If you are not going to change in readme, there is no point in merging my PR.

you said "majority of the users would be running bash", there lies the problem.

Why even assume that ? why not go on with the fact that everyone will have sh ?

sh will be available everywhere, regardless of whatever unix based system you are running.

That's what i was trying to do, the whole "POSIX compliant" charade is for that sole purpose, making it work everywhere.

Also, I don't mind doing something a little difficult, but if it doesn't make sense, well that's out my range. I am not trying to argue, but making sane statements, i will be happy if you prove me wrong.

I will do the required changes after we are on the same boat, hope you understand. I do love this script for making installation of micro so easy, but it is what it is, thank you.

**Comment by benweissmann** [comment]
The main way users run this script is with `curl https://getmic.ro | bash` though -- very few users download the script and run it with `bash -i`. If you have an interactive part of the script and hit that when running it with `curl https://getmic.ro | bash`, it won't work -- so I think it's a better user experience to explain how to re-run it with an environment variable.

I can say with some confidence that the vast majority of people who want to use getmic.ro have `bash`, because there's about 10k users / month, and so far I haven't heard from anyone who has a problem with `bash`. My goal here is to provide the most reliable, best-tested option for users, many of who are a lot less technically included / able to debug stuff than you and I -- part of the value of Micro is that it's a very approachable CLI editor. So I'd like to keep the main instructions as `| bash` because that's what's been tested the most. How about we move the stuff about checking the checksum, and a note that you can run this as `| sh` with any POSIX-compatible shell  under a new `# Advanced Options` header? That way users can get a clear, as-reliable-as-possible instruction up top, and more advanced users who want to run it on systems without `bash` can know that that's possible and tested as well.

**Comment by Akianonymus** [comment]
Just changed the script, nothing else.

something wrong with the tests ?

**Comment by benweissmann** [comment]
Just pushed a fix for the tests, thanks for the contribution!

**Comment by Akianonymus** [comment]
@benweissmann Thank you

Some notes for your previous comments

When i referencing to the cat index.sh | bash in test scripts, that is actually useless use of cat. Just a little thing, nothing else.

**Pull request merged**
