### PR TITLE
Rework for bash -s nightly

### PR DESCRIPTION
**Pull request by God-damnit-all**
I wanted some experience working with bash scripts, and I figured adding a nightly option was a good way to go about it.

Using jq to parse the JSON would've made it easy, but given just about every Linux installation has Python in some form, passing a one-liner to grab the relevant URLs from the GitHub API made sense. The only problem is that the command requires an additional import when using Python 2. So I gave it the command priority python3→python2→python, with the latter two receiving the additional import.

Finally, I realized that if I was going to do it like this, I should revise the function for stable releases as well, to better match the Nightly function.

Lastly, I wanted to get rid of the temporary files and have it just extract directly into the working directory. bsdtar and GNU tar both support `--strip`, but they handle filtering the contents differently. In bsdtar, `--wildcards` is assumed, but you need `--include` for whitelist filtering. And, of course, it's the other way around in GNU Tar. So I added a check for that and tested it with both, works good.

In order to download the nightly build, it would be the same command as before, just with `-s nightly` at the end.

### CODE REVIEW

**Comment by God-damnit-all** [comment]
You can safely ignore Travis's complaint - for that particular line, `"$@"` is considered best practice. It can be changed to `"$*"` if need be, though.

**Comment by God-damnit-all** [comment]
@zyedidia Do you have merging permission for this project? If so, I'd like you to review this. It seems @benweissmann isn't available.

**Comment by zyedidia** [comment]
Sorry I don't have write access to this repo. The PR looks good to me though.

**Comment by benweissmann** [comment]
Hey, sorry about the delay on this, and thank you for your contribution! 

A couple things that need to happen before I can merge this:

- Fix the current tests, either by adjusting the linting config or adjusting your code to match the current linting config. I'm not willing to merge anything that doesn't pass tests, because then it's hard to tell if future PRs are introducing a regression or if they're just hitting the error from this PR.

- Update CI to test this new nightly download pipeline in the same way we test the latest stable download -- CI should test that across platforms it can successfully download and run nightly micro.

- Update documentation so folks know about this feature! Along those lines, it looks like the argument parsing just accepts `nightly` anywhere in the argument list, but I think we'll want to be a little stricter to give us more flexibility to add other options in the future. Maybe check for explicitly `--nightly`?

Thanks again for contributing, and sorry about the slow response!

**Comment by God-damnit-all** [comment]
* Update CI to test this new nightly download pipeline in the same way we test the latest stable download -- CI should test that across platforms it can successfully download and run nightly micro.

Could you elaborate on what you mean by this?

**Comment by benweissmann** [comment]
You should update the CI configuration to test this new `nightly` option. You can find our Travis CI config here: https://github.com/benweissmann/getmic.ro/blob/master/.travis.yml and you'll see that it's running this script: https://github.com/benweissmann/getmic.ro/blob/master/ci/runTest.sh

You should update that so Travis tests both the existing behavior -- downloading and running the stable version of micro -- as well as your new behavior -- downloading and running the nightly version of micro.

**Comment by God-damnit-all** [comment]
Eh, sorry, I'll pass.

**Comment by benweissmann** [comment]
OK! Feel free to re-open if you find some more time and want keep working on this.

**Pull request closed without merging**
