### PR TITLE
Add Wget support

### PR DESCRIPTION
**Pull request by xearonet**
Hi, I add support for Wget in getmic script.

BTW script is extremely useful. I use them very often.

BR
xearonet

### CODE REVIEW

**Review by anonyco — CHANGES_REQUESTED** [review]
I support these changes, but I think you should change line 29 to ` if command -v curl > /dev/null; then`

**Comment by benweissmann** [comment]
Hi! Sorry about the slow response.

I'd love to merge this in, but you'll need to add some automated tests to the CI system. I'd suggest finding a docker image or two that have wget but not curl, and then adjusting this step of the CI pipeline: https://github.com/benweissmann/getmic.ro/blob/master/.github/workflows/test.yml#L59 -- note that that run https://github.com/benweissmann/getmic.ro/blob/master/ci/runDockerInner.sh which attempts to install `curl`, so you'll need to create another version of the script or have an env var or something to have it not install curl.

**Comment by xearonet** [comment]
> I support these changes, but I think you should change line 29 to ` if command -v curl > /dev/null; then`

Yes. I'm aware of this. I want it to be as portable as possible.
Please take a look at this thread: [https://stackoverflow.com/questions/592620/how-can-i-check-if-a-program-exists-from-a-bash-script](https://stackoverflow.com/questions/592620/how-can-i-check-if-a-program-exists-from-a-bash-script)

**Comment by xearonet** [comment]
> Hi! Sorry about the slow response.

No worry. We are busy people 😃 
> 
> I'd love to merge this in, but you'll need to add some automated tests to the CI system. I'd suggest finding a docker image or two that have wget but not curl, and then adjusting this step of the CI pipeline: https://github.com/benweissmann/getmic.ro/blob/master/.github/workflows/test.yml#L59 -- note that that run https://github.com/benweissmann/getmic.ro/blob/master/ci/runDockerInner.sh which attempts to install `curl`, so you'll need to create another version of the script or have an env var or something to have it not install curl.

OK. I'll look at this when find some free time 😉

**Comment by benweissmann** [comment]
I'm going to close this issue for now since it looks like it's abandoned. Feel free to re-open if you have some time to work on it!

**Pull request closed without merging**
